import { NextResponse } from 'next/server';

/**
 * AI Meme Generation API
 * Currently implements a high-fidelity prompt wrapper.
 * For production, connect to OpenAI DALL-E or Stability AI.
 */
export async function POST(req: Request) {
    try {
        const { prompt } = await req.json();

        if (!prompt) {
            return NextResponse.json({ error: "Prompt is required" }, { status: 400 });
        }

        console.log(`Generating AI Meme with prompt: ${prompt}`);

        // MOCK AI GENERATION LOGIC 
        // In a real implementation, you would call OpenAI/Stability here
        // We simulate a 2-second generation process
        await new Promise(resolve => setTimeout(resolve, 2000));

        // Use a curated set of aesthetic placeholders that fit the "Neon-Meme" theme
        const placeholders = [
            'https://api.dicebear.com/7.x/pixel-art/svg?seed=doge&backgroundColor=b6e3f4',
            'https://api.dicebear.com/7.x/identicon/svg?seed=moonshot&backgroundColor=6366f1',
            'https://api.dicebear.com/7.x/shapes/svg?seed=pepe&backgroundColor=10b981'
        ];
        
        const generatedUrl = placeholders[Math.floor(Math.random() * placeholders.length)];

        return NextResponse.json({ 
            imageUrl: generatedUrl,
            message: "Meme successfully generated by AI engine."
        });

    } catch (error) {
        console.error("AI Generation Error:", error);
        return NextResponse.json({ error: "Failed to generate meme." }, { status: 500 });
    }
}
